---
- name: Install Jenkins, Java, and Python
  hosts: Project1
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Python
      apt:
        name: python3
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      when: ansible_pkg_mgr == 'apt'
